### ISSUE TITLE
jekyll 3.0 compatibility

### ISSUE THREAD

**Issue by stevecrozz** [octopress/minify-html#10]
I see the octopress-minify-html gem does not allow it to be installed against jekyll 3.0 as it is locked to jekyll ~> 2.0:
https://github.com/octopress/minify-html/blob/master/octopress-minify-html.gemspec#L24

Is this due to a known compatibility issue or should newer versions of jekyll be allowed?

**Comment by imathis** [comment]
It relies on Octopress-hooks which has been folded into Jekyll 3 and changed a bit. I should release a new version of this to support both Jekyll 2 & 3. I'll see if I can get something out tonight.

**Comment by imathis** [comment]
I've released 1.3.0 which adds compatibility with Jekyll 3.

**Comment by stevecrozz** [comment]
Nice. I'll give it a whirl.
