### ISSUE TITLE
Cannot use with jekyll-assets

### ISSUE THREAD

**Issue by iamcarrico** [octopress/minify-html#5]
I have been using ixti/jekyll-assets for sometime to handle assets in a site. When I try and enable jekyll-minify-html however, I get a barrage of errors from YUI that there are issues. I have no idea what is causing them, except that a little bit of googling says it is because YUI is being given assets that are empty. 

I am going to assume it is because html-press is doing more than just minifying the html. But for the purposes of this plugin, it should be limited to just html.

Errors I get:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.getToken(JavaScriptCompressor.java:578)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSymbolTree(JavaScriptCompressor.java:1094)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.compress(JavaScriptCompressor.java:556)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:186)
	... 5 more
```

**Comment by imathis** [comment]
I think I have an idea of how I can fix this. Taking a look. Thanks :)

**Comment by iamcarrico** [comment]
:+1:

**Comment by imathis** [comment]
I believe I may have fixed this. Before I was monkey-patching Jekyll in a way that probably conflicted with jekyll-assets. I've rewritten this plugin and I think that shouldn't be an issue now. If you could update and let me know, I'd really appreciate it.

Note: I've moved development of this plugin under Octopress and the new gem is named `octopress-minify-html` but it should work just the same.

**Comment by iamcarrico** [comment]
I will do some testing of it tonight— 

Question: Why add the octopress prefix? It makes it seem that it can't be used on non-octopress sites?

**Comment by iamcarrico** [comment]
I tested it again, and still have the error. Let me see if i can create a repo that you can test it in—

**Comment by imathis** [comment]
Perhaps the Jekyll team wants to eventually release a first-party version of this. I'd rather not dominate the Jekyll namespace with my plugins. Hopefully soon Octopress will no longer be seen as a thing that is separate from the Jekyll community. It's just the name I'm putting on all the plugins I build for Jekyll and hoping that the Octopress namespace will be seen as a sign of quality.

**Comment by imathis** [comment]
Thanks for the update. I'll be delighted to troubleshoot it and get a fix out.

**Comment by iamcarrico** [comment]
One repo— two commits. Initial commit running 'gulp build' or 'bundle exec jekyll build' will work. Second commit (with JavaScript)... issues happen. 

Good luck. We are all counting on you.

**Comment by iamcarrico** [comment]
![image](https://cloud.githubusercontent.com/assets/1394978/5656008/f0d0e14e-969b-11e4-9118-09d2ce78ee79.png)

**Comment by iamcarrico** [comment]
Sorry, I forgot the link... https://github.com/iamcarrico/minify-html-test

**Comment by imathis** [comment]
Ah, you're right, that's a mess. It looks like it's something far deeper than my code. Somehow something in YUI is blowing up. I gotta say, I don't know where to begin with this one. Maybe I can find a different html compressor for this plugin.

Side note: This jekyll-assets plugin has a ton of stuff going on. It's like a mini rails pipeline. If you're looking for something simpler, maybe check out octopress-asset-pipeline. It accomplishes a basic subset of jekyll-assets but it uses uglifier instead of YUI and has a smaller dependency chain.

**Comment by imathis** [comment]
So yeah, I'm not going to be able to fix this—at least, not until I have time to research other html compressors. I'm sorry. :(

**Comment by iamcarrico** [comment]
Thank you for trying—I will work on it as well. 


Side note: I looked into both plugins, and needed some of the functionality in the jekyll-assets plugin. But I did to testing a long time back, and the YUI errors are not coming from jekyll-assets, but the html press.

**Comment by imathis** [comment]
I'm mainly relying on an external process for minifying HTML, but if you're right that HTML-press is using YUI, I'm going to try to find a new compressor. Thanks.
