### ISSUE TITLE
Add configuration for exceptions

### ISSUE THREAD

**Issue by anselmh** [octopress/minify-html#9]
It would be great to define exceptions like the minifier should not strip specific attributes like `input type="text"` when specified.

Would that be possible?

**Comment by paulrobertlloyd** [comment]
Another example would be SSI directives, i.e. , which use HTML comments. Tough one!

**Comment by imathis** [comment]
Both of these issues should probably be added as an issue on [HtmlPress](https://github.com/stereobooster/html_press) (the compression engine that this plugin uses).

@anselmh, Take a look at [this script](https://github.com/stereobooster/html_press/blob/master/lib/html_press/html.rb#L255) where I believe they're stripping the `type='text'`.

I'll add a configuration that passes options through to HtmlPress.

**Comment by imathis** [comment]
I've just released 1.2.4 which lets you [pass options to HTML press](https://github.com/octopress/minify-html#htmlpress-configuration). That won't help with what you're asking about right now, but perhaps if your issues on HtmlPress get merged you can set options in this way.

That's the best I can do for now, so I'm going to close this issue. Cheers!

**Comment by anselmh** [comment]
Thanks man! :)

**Comment by imathis** [comment]
You bet!

I looked at HtmlPress again and dang; it's been a while since that got any attention. Last touched 2 years ago and several open issues, with no responses. Hmm. Perhaps I need to find a different compressor for this project. Ugh.

**Comment by paulrobertlloyd** [comment]
Thanks @imathis!

> I looked at HtmlPress again and dang; it's been a while since that got any attention. Last touched 2 years ago and several open issues, with no responses. Hmm

Story of my life! ;-)
